### ISSUE TITLE
false negative, possibly due to an else statement

### ISSUE THREAD

**Issue by josharian** [griesemer/tryhard#2]
This should be safe to transform:

```go
			if err := dump(w, n, rec); err != nil {
				return err
			} else {
				fmt.Fprintln(w)
			}
```

to:

```go
			try(dump(w, n, rec)
			fmt.Fprintln(w)
```

(The key restriction is that `err` does not appear in the `else` block.

**Comment by griesemer** [comment]
Indeed. And if the assignment is using `=` instead of `:=`, it should be ok to transform even if `err` appears in the `else` block. Both these assume there are no aliases to `err`.

**Comment by codenoid** [comment]
should we close

**Comment by griesemer** [comment]
@codenoid Yes. Thanks for reminding me.

Closing this issue as "wontfix" since we have abandoned the `try` proposal.
