### ISSUE TITLE
offer the more common -w for write

### ISSUE THREAD

**Issue by philoserf** [griesemer/tryhard#5]
-r rewrite doesn't follow the common golang model of -w write found in core utilities like gofmt, goimports, or goreturns. 

as a nod to common practice add it and deprecate -r for the next release

**Comment by griesemer** [comment]
It's really a `r`ewrite, not so much a formatted `w`rite, hence the `-r`. But fine. I'll change it in the next round of changes.

**Comment by philoserf** [comment]
It is exactly what gofmt does with -w much like `gofmt -s -w`

**Comment by philoserf** [comment]
Not attached to it. Just found the -r surprising

**Comment by philoserf** [comment]
I found a few examples that use -r, replace. Who know what is right with names?
