### ISSUE TITLE
Invalid conversion when err is used later in code

### ISSUE THREAD

**Issue by vearutop** [griesemer/tryhard#6]
```go
	values, err := c.Encoder.Encode(row)
	if err != nil {
		return err
	}

	if nil == c.columns {
		_, c.columns, err = c.Encoder.EncodeWithColumns(row)
		if err != nil {
			return err
		}

		err = c.CSVWriter.Write(c.columns)
		if err != nil {
			return err
		}

		c.row = make([]string, len(values))
	}
```
is converted to 
```go
	values := try(c.Encoder.Encode(row))

	if nil == c.columns {
		_, c.columns, err = c.Encoder.EncodeWithColumns(row)
		if err != nil {
			return err
		}

		err = c.CSVWriter.Write(c.columns)
		if err != nil {
			return err
		}

		c.row = make([]string, len(values))
	}
```
which is now broken due to `err` is being reused later.

Also it seems the other two `return err` could be converted to `try`.

**Comment by griesemer** [comment]
@vearutop Thanks for this report!

Unfortunately, `tryhard` is not smart enough to avoid the invalid conversion - there's no analysis of the variable's scopes, etc. The tool is meant for exploratory purposes, not as a definitive converter that works in all cases.

But the missing conversions inside the `if` statement are a clear (and embarrassing) oversight. I have a fix coming shortly.

**Comment by griesemer** [comment]
@vearutop FYI, this fix uncovered quite a few additional `try` opportunities in the std library: https://go-review.googlesource.com/c/go/+/182717/4..5 (not all changes are due to `try` rewrites, some changes are simply updates of the source).

**Comment by vearutop** [comment]
hope to see try available in vanilla Go soon! :)
