### ISSUE TITLE
additional stats

### ISSUE THREAD

**Issue by networkimprov** [griesemer/tryhard#8]
[Pasted from post on the `try()` thread]

The following stats would be valuable...

1. the number of call sites yielding an error
1. the number of single-statement `if err != nil [&& ...]` handlers (candidates for `on err` https://github.com/golang/go/issues/32611)
1. the number of those which return anything (candidates for `defer` https://github.com/golang/go/issues/32676)
1. the number of those which return `err` (candidates for `try()`)
1. the number of those which are in exported functions of non-main packages (likely false positive)

**Comment by griesemer** [comment]
Closing. `try` proposal was abandoned.
